VehicleReservation/ViewModels/DriverViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace VehicleReservation.ViewModels
{
    public class DriverViewModel
    {
        public int DriverID { get; set; }

        [Required(ErrorMessage = "Last Name is required")]
        [RegularExpression("^[a-zA-Z\\.\\- +]*$", ErrorMessage = "Only Letters are accepted")]
        public string DriverLastName { get; set; }

        [Required(ErrorMessage = "First Name is required")]
        [RegularExpression("^[a-zA-Z\\.\\- +]*$", ErrorMessage = "Only Letters are accepted")]
        public string DriverFirstName { get; set; }

        [Required(ErrorMessage = "Mobile Number is required")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Only numbers are accepted")]
        [StringLength(11, MinimumLength = 11, ErrorMessage = "Must be 11 characters long")]
        public string MobileNumber { get; set; }

        [Required(ErrorMessage = "Driver's License is required")]
        public string DriverLicense { get; set; }

        //[DataType(DataType.Date)]
        [Required(ErrorMessage = "License Expiry is required")]
        //[DisplayFormat(DataFormatString = "{0:YYYY-MM-DD)")]
        public DateTime? LicenseExpiry { get; set; }

        [Required(ErrorMessage = "Business Unit ID is required")]
        public string BusinessUnit { get; set; }
        public bool IsActive { get; set; }

        public int? BusinessUnitID { get; set; }

        public System.DateTime DateRegistered { get; set; }

        public string FullName
        {
            get { return DriverLastName + ", " + DriverFirstName; }
        }

        public List<Users> Users { get; set; }

        public int? ModifiedBy { get; set; }
        public int? UserID { get; set; }
        public string Name { get; set; }
    }
}

VehicleReservation/Controllers/DriverController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VehicleReservation.Repository;
using VehicleReservation.ViewModels;
using Newtonsoft.Json;
using System.Collections.Specialized;

namespace VehicleReservation.Controllers
{
    public class DriverController : Controller
    {
        private VehicleReservationEntities db = new VehicleReservationEntities();
        //LIST
        public ActionResult List(string searchString)
        {
            if (Request.Cookies["UserID"] == null || Request.Cookies["token"] == null)
            {
                return Redirect("https://www.portal.smsgt.com/webportal/index.php/login");
            }


            var repo = new ManagementRepository();
            var model = repo.ListDriver();

            DriverListVM DLVM = new DriverListVM();
            DLVM.Drivers = new List<DriverViewModel>();

            DLVM.Drivers = (from data in model
                            select new DriverViewModel()
                            {
                                DriverID = data.DriverID,
                                   DriverLicense = data.DriverLicense,
                                   Name = data.Name,
                                   LicenseExpiry = data.LicenseExpiry,
                                   BusinessUnit = data.BusinessUnit,
                                   MobileNumber = data.MobileNumber


                               }).ToList();

            return View(DLVM);
        }

        //DETAILS
        public ActionResult Details(int id)
        {

            if (Request.Cookies["UserID"] == null || Request.Cookies["token"] == null)
            {
                return Redirect("https://www.portal.smsgt.com/webportal/index.php/login");
            }


            var repo = new ManagementRepository();
            var model = repo.GetDriverDetails(id);
            var DVM = new DriverViewModel();

            DVM.DriverID = model.DriverID;
            DVM.Name = model.Name;
            DVM.DriverLicense = model.DriverLicense;
            DVM.LicenseExpiry = model.LicenseExpiry;
            DVM.MobileNumber = model.MobileNumber;
            DVM.BusinessUnit = model.BusinessUnit;

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            return View(DVM);
        }

        //ADD
        public async Task<ActionResult> Add()
        {

            if (Request.Cookies["UserID"] == null || Request.Cookies["token"] == null)
            {
                return Redirect("https://www.portal.smsgt.com/webportal/index.php/login");
            }


            DriverViewModel VM = new DriverViewModel();
            string token = Convert.ToString(Request.Cookies["token"].Value.ToString());


            DataService DS = new DataService();
            VM.Users = await DS.GetUsers(token);

            int? rb = Convert.ToInt32(Request.Cookies["UserID"].Value.ToString());
            VM.ModifiedBy = rb;


            return View(VM);
        }

        public ActionResult _Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult add_driver()
        {
            string msg = "";
            var repo = new ManagementRepository();
            var driver = new Driver();
            
            driver.Name = Request.Form["driver_name"];
            driver.MobileNumber = Request.Form["mobile"];
            driver.DriverLicense = Request.Form["license_no"];
            driver.LicenseExpiry = DateTime.Parse(Request.Form["expiry_date"]);

            repo.AddDriver(driver);
            
            return Json(msg, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult edit_driver(int id)
        {
            string msg = "";
            var repo = new ManagementRepository();
            var driver = new Driver();

            driver.Name = Request.Form["driver_name"];
            driver.MobileNumber = Request.Form["mobile"];
            driver.DriverLicense = Request.Form["license_no"];
            driver.LicenseExpiry = DateTime.Parse(Request.Form["expiry_date"]);
            driver.DriverID = id;

            repo.UpdateDriver(driver);

            return Json(msg, JsonRequestBehavior.AllowGet);
        }

        public ActionResult driver_view(int id)
        {
            var repo = new ManagementRepository();
            var model = repo.GetDriverDetails(id);
            var DVM = new DriverViewModel();

            DVM.DriverID = model.DriverID;
            DVM.Name = model.Name;
            DVM.DriverLicense = model.DriverLicense;
            DVM.LicenseExpiry = model.LicenseExpiry;
            DVM.MobileNumber = model.MobileNumber;
            DVM.BusinessUnit = model.BusinessUnit;

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            return View(DVM);
        }

        [HttpPost]
        public ActionResult driver_details(int driver_id)
        {
            var driver = (from d in db.Drivers
                          where d.DriverID == driver_id
                          select new {
                              d.Name,
                              d.MobileNumber,
                              d.LicenseExpiry,
                              d.DriverLicense,
                         }).SingleOrDefault();
            return Json(driver, JsonRequestBehavior.AllowGet);
        }

        //[HttpPost]
        //public ActionResult Add(DriverViewModel DVM)
        //{
        //    var repo = new ManagementRepository();
        //    var driver = new Driver();


        //    driver.Name = DVM.Name;
        //    driver.DriverLicense = DVM.DriverLicense;
        //    driver.LicenseExpiry = DVM.LicenseExpiry;
        //    driver.MobileNumber = DVM.MobileNumber;
        //    driver.BusinessUnitID = DVM.BusinessUnitID;
        //    driver.BusinessUnit = DVM.BusinessUnit;
        //    driver.UserID = DVM.UserID;
        //    driver.DateRegistered = DateTime.Now;
        //    driver.IsActive = false;
        //    driver.ModifiedBy = DVM.ModifiedBy;


        //    repo.AddDriver(driver);

        //    return RedirectToAction("List");
        //}

        //EDIT
        [HttpGet]
        public async Task<ActionResult> Edit(int? id)
        {


            if (Request.Cookies["UserID"] == null || Request.Cookies["token"] == null)
            {
                return Redirect("https://www.portal.smsgt.com/webportal/index.php/login");
            }


            var repo = new ManagementRepository();
            var DVM = new DriverViewModel();
            string token = Convert.ToString(Request.Cookies["token"].Value.ToString());



            DataService DS = new DataService();
            DVM.Users = await DS.GetUsers(token);
            int? rb = Convert.ToInt32(Request.Cookies["UserID"].Value.ToString());



            Driver editDriver = db.Drivers.Find(id);
            //   repo.UpdateDriver(editDriver);
            DVM.DriverID = editDriver.DriverID;
            DVM.Name = editDriver.Name;
            DVM.DriverLicense = editDriver.DriverLicense;
            DVM.LicenseExpiry = editDriver.LicenseExpiry;
            DVM.MobileNumber = editDriver.MobileNumber;
            DVM.BusinessUnit = editDriver.BusinessUnit;
            DVM.BusinessUnitID = editDriver.BusinessUnitID;
            DVM.UserID = editDriver.UserID;
            DVM.ModifiedBy = rb;

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            return View(DVM);
        }

        [HttpPost]
        public ActionResult Edit(DriverViewModel DVM)
        {

            var repo = new ManagementRepository();
            var driver = new Driver();
            using (var db = new VehicleReservationEntities())
            { 
                var existingDriver = (from data in db.Drivers
                                      where data.DriverID == DVM.DriverID
                                      select data).FirstOrDefault();

                existingDriver.DriverID = DVM.DriverID;
                existingDriver.Name = DVM.Name;
                existingDriver.DriverLicense = DVM.DriverLicense;
                existingDriver.LicenseExpiry = DVM.LicenseExpiry;
                existingDriver.MobileNumber = DVM.MobileNumber;
                existingDriver.BusinessUnit = DVM.BusinessUnit;
                existingDriver.BusinessUnitID = DVM.BusinessUnitID;
                existingDriver.UserID = DVM.UserID;
                existingDriver.ModifiedBy = DVM.ModifiedBy;

                repo.UpdateDriver(existingDriver);
            }




            return RedirectToAction("List");
            
        }

        

        //public String Users(string start, string end)
        //{
        //    UserList UL = new UserList();
        //    UL.Users = new List<UsersViewModel>();

        //    UL.Users = (from data in db.Drivers
        //                select new UsersViewModel()
        //                {
        //                    DriverID = data.DriverID,
        //                    DriverLastName = data.DriverLastName,
        //                    DriverFirstName = data.DriverFirstName

        //                }).ToList();
        //    var json = JsonConvert.SerializeObject(UL.Users);
        //    return json;

        //}

        //static HttpClient client = new HttpClient();

        //static async Task RunAsync()
        //{
        //    client.BaseAddress = new Uri("https://www.portal.smsgt.com/onesapi/api/attendance/Getusers");
        //    client.DefaultRequestHeaders.Accept.Clear();
        //    client.DefaultRequestHeaders.Accept.Add(

VehicleReservation/Views/Driver/Add.cshtml
@model VehicleReservation.ViewModels.DriverViewModel
@{
    ViewBag.Title = "Add Driver";
}

@section Jscripts{

    @*<script type="text/javascript">
            $(function () {
                $("#LicenseExpiry").datepicker({
                    changeMonth: true,
                    changeYear: true,
                    dateFormat: "yy-MM-dd"

                }
                ).datepicker("setDate", new DateTime());
            });
        </script>

        <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>*@
    <script type="text/javascript">
        $(function () {
            $('#datetimepicker').datetimepicker({
                format: 'L',
                minDate: moment(),
                ignoreReadonly: true

                //useCurrent: true
            });
        });


        $(function () {
            $('#iDrivers').select2().change(function () {
                buid = ($(this).find(':selected').data('buid'));
                buname = ($(this).find(':selected').data('buname'));
                name = ($(this).find(':selected').data('name'));


                $("#BusinessUnitID").val(buid);
                $("#BusinessUnit").val(buname);
                $("#Name").val(name);

            });
            @*$('.select-box').select2({
                ajax: {
                    url: '@Url.Action("GetUsers", "Driver")',
                    datatype: 'json',
                    success: function (data) {
                        var mapping = $.map(data, function (obj) {
                            obj.id = obj.id || obj.UserID;
                            obj.text = obj.text || obj.Name;

                            return obj;

                        });
                    }
                }
            });*@
        });


    </script>

}

<div class="row">
    <div class="col-md-12 ">
        <div class="panel" style="margin-top:3%; margin-bottom: 5%;">
            <div class="panel-heading">
                <div class="panel-title">
                </div>

                <div class="panel-body">

                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


                        <div class="col-md-12">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <div class="form-group control-label">
                                        <label>
                                            Driver
                                        </label>
                                    </div>

                                    <select id="iDrivers" name="UserID" style="width: 100%">
                                        @foreach (var item in Model.Users)
                                        {

                                            <option value="@item.UserID" data-buid="@item.BusinessUnitID" data-buname="@item.BusinessUnit"
                                                    data-name="@item.Name">
                                                @item.Name
                                            </option>

                                        }
                                    </select>
                                    @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
                                    @Html.HiddenFor(model => Model.ModifiedBy)
                                    @Html.HiddenFor(model => Model.BusinessUnitID, new { @id = "BusinessUnitID" })
                                    @Html.HiddenFor(model => Model.Name, new { @id = "Name" })

                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <div class="form-group control-label ">
                                        <label>
                                            Business Unit
                                        </label>
                                    </div>
                                    <div>
                                        @Html.EditorFor(model => model.BusinessUnit, new { htmlAttributes = new { @class = "form-control", @type = "text", @autocomplete = "off" , @id = "BusinessUnit", @readonly = "true"} })
                                        @Html.ValidationMessageFor(model => model.BusinessUnit, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="form-group">
                                    <div class="form-group control-label">
                                        <label>
                                            Mobile Number
                                        </label>
                                    </div>
                                    <div>
                                        @Html.EditorFor(model => model.MobileNumber, new { htmlAttributes = new { @class = "form-control", @autocomplete = "off" } })
                                        @Html.ValidationMessageFor(model => model.MobileNumber, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                        </div>
                                        @*<div class="col-md-4">
                                                <div class="form-group">
                                                    <div class="form-group control-label">
                                                        <label>
                                                            Last Name
                                                        </label>
                                                    </div>
                                                    <div>
                                                        @Html.EditorFor(model => model.DriverLastName, new { htmlAttributes = new { @class = "form-control", @autocomplete = "off" } })
                                                        @Html.ValidationMessageFor(model => model.DriverLastName, "", new { @class = "text-danger" })
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <div class="form-group control-label">
                                                        <label>
                                                            First Name
                                                        </label>
                                                    </div>
                                                    <div>
                                                        @Html.EditorFor(model => model.DriverFirstName, new { htmlAttributes = new { @class = "form-control", @autocomplete = "off" } })
                                                        @Html.ValidationMessageFor(model => model.DriverFirstName, "", new { @class = "text-danger" })

                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <div class="form-group control-label ">
                                                        <label>
                                                            Business Unit ID
                                                        </label>
                                                    </div>
                                                    <div>
                                                        @Html.EditorFor(model => model.BusinessUnit, new { htmlAttributes = new { @class = "form-control", @type = "text", @style = "width:50%", @autocomplete = "off" } })
                                                        @Html.ValidationMessageFor(model => model.BusinessUnit, "", new { @class = "text-danger" })
                                                    </div>
                                                </div>
                                            </div>*@


                                        <div class="col-md-12">
                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <div class="form-group control-label">
                                                        <label>
                                                            Driver's License No.
                                                        </label>
                                                    </div>
                                                    <div>
                                                        @Html.EditorFor(model => model.DriverLicense, new { htmlAttributes = new { @class = "form-control", @autocomplete = "off" } })
                                                        @Html.ValidationMessageFor(model => model.DriverLicense, "", new { @class = "text-danger" })
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <div class="form-group control-label">
                                                        <label>
                                                            License Expiry Date
                                                        </label>
                                                    </div>
                                                    <div>
                                                        <div class="form-group">
                                                            <div class="input-group date" id="datetimepicker">
                                                                @Html.EditorFor(model => model.LicenseExpiry, new { htmlAttributes = new { @class = "form-control", @readonly = "true" } })
                                                                <span class="input-group-addon">
                                                                    <span class="glyphicon glyphicon-calendar"></span>
                                                                </span>
                                                            </div>
                                                            @Html.ValidationMessageFor(model => model.LicenseExpiry, "", new { @class = "text-danger" })

                                                        </div>
                                                    </div>
                                                </div>
                                            </div>

                                        </div>
                                        <div class="form-group">
                                            <div class="col-sm-12">
                                                <input type="submit" value="Save" class="btn btn-success" />
                                                @Html.ActionLink("Back To List", "List", null, new { @class = "btn btn-primary btn-large" })


                                            </div>
                                        </div>
                    }

                </div>
            </div>

        </div>

    </div>




</div>

VehicleReservation/Views/Driver/Details.cshtml
@model VehicleReservation.ViewModels.DriverViewModel
@{
    ViewBag.Title = "Details";
}

<div class="row">
    <div class="col-md-12 ">
        <div class="panel" style="margin-top:3%; margin-bottom: 5%;">
            <div class="panel-heading">
                <div class="panel-title">
                </div>

                <div class="panel-body">

                    <div class="col-md-12">
                        <div class="col-md-4">
                            <div class="form-group">
                                <div class="form-group control-label">
                                    <label>
                                       Name
                                    </label>
                                </div>
                                <div>
                                    @Html.DisplayFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                </div>
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="form-group">
                                <div class="form-group control-label ">
                                    <label>
                                        Business Unit 
                                    </label>
                                </div>
                                <div>
                                    @Html.DisplayFor(model => model.BusinessUnit, new { htmlAttributes = new { @class = "form-control", @type = "text", @style = "width:50%" } })
                                </div>
                            </div>
                        </div>


                        <div class="col-md-4">
                            <div class="form-group">
                                <div class="form-group control-label">
                                    <label>
                                        Mobile Number
                                    </label>
                                </div>
                                <div>
                                    @Html.DisplayFor(model => model.MobileNumber, new { htmlAttributes = new { @class = "form-control" } })
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-12">
                        <div class="col-md-4">
                            <div class="form-group">
                                <div class="form-group control-label">
                                    <label>
                                        Driver's License No.
                                    </label>
                                </div>
                                <div>
                                    @Html.DisplayFor(model => model.DriverLicense, new { htmlAttributes = new { @class = "form-control" } })
                                </div>
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="form-group">
                                <div class="form-group control-label">
                                    <label>
                                        License Expiry Date
                                    </label>
                                </div>
                                <div>
                                    @*@Html.DisplayFor(model =>  model.LicenseExpiry, new { htmlAttributes = new { @class = "form-control" } })*@
                                   @Model.LicenseExpiry.Value.ToShortDateString()
                                 </div>
                            </div>
                        </div>
                    </div>
                    @Html.ActionLink("Back To List", "List", null, new { @class = "btn btn-primary btn-large" })


                </div>
            </div>

        </div>




    </div>

</div>

VehicleReservation/Views/Driver/_Add.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<style>
    .form-row{
        margin-right:10px;
        float:left;
    }
</style>

<div class="row">

    <div class="panel">
        <div class="panel-heading">
            <div class="panel-title">
            </div>

            <div class="panel-body">

                <form id="form_driver">

                    <div class="form-row">
                        <div class="form-group">
                            <div class="form-group control-label">
                                <label>
                                    Driver
                                </label>
                            </div>
                            <div>
                                <input type="text" placeholder="Driver" class="form-control" id="driver" style="width:235px;" required/>
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group">
                            <div class="form-group control-label">
                                <label>
                                    Mobile Number
                                </label>
                            </div>
                            <div>
                                <input type="text" class="form-control" id="mobile" placeholder="Mobile Number" style="width:235px;" required/>
                            </div>
                        </div>
                    </div>


                    <div class="form-row">
                        <div class="form-group">
                            <div class="form-group control-label">
                                <label>
                                    Driver's License No.
                                </label>
                            </div>
                            <div>
                                <input type="text" class="form-control" placeholder="Driver's License No." id="license_no" style="width:235px;" required/>
                            </div>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-group">
                            <div class="form-group control-label">
                                <label>
                                    License Expiry Date
                                </label>
                            </div>
                            <div>
                                <input type="text" class="form-control" placeholder="Expiry Date" id="expiry_date" style="width:235px;" required/>
                            </div>
                        </div>
                    </div>
                </form>

            </div>
        </div>

    </div>







</div>